### ISSUE TITLE
Tell people to put the encrypted variable in env/matrix

### ISSUE THREAD

**Issue by asmeurer** [gforsyth/doctr#34]
I'm a little unclear how it works (see https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables), but I think it is possible to make the encrypted variable only avaiable for the specific build in the matrix, which is probably a good idea to avoid leaking it.

**Comment by gforsyth** [comment]
I think that the rough format should be (looking at [this](https://docs.travis-ci.com/user/customizing-the-build#Explicity-Including-Jobs)):

```
matrix:
    include:
    - DOCS="true"
      secure: <encrypted key>
    - TESTS="true"
```
